version: "3"
services:
  webapi:
    container_name: flask
    image: webapi
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "False"
      APP_PORT: 5000
      MONGODB_DATABASE: admin
      MONGODB_USERNAME: user
      MONGODB_PASSWORD: lKt77eg5fIc2
      MONGODB_HOSTNAME: mongodb
    volumes:
      - ./app:/var/www
    depends_on:
      - mongodb
    networks:
      - frontend
      - backend
    ports:
      - 5000:5000
  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: lKt77eg5fIc2
      MONGO_INITDB_DATABASE: admin
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend
  tests:
    image: mrexpen/planet_olymp_phase1
    pull_policy: always
    container_name: tests
    ports:
      - "8090:8080"
    depends_on:
      - webapi
    environment:
      SERVER_URL: "http://webapi:5000"
      STAGE: all
    networks:
      - frontend
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local
